# Jekyll configuration

name: Bartosz Gladecki
description: Full Stack JavaScript/React, Ruby on Rails and Elixir developer

# Url is currently only used only for the RSS feed in feed.xml
url: http://gladecki.pl
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

share:
  facebook: true
  twitter: false
  gplus: false
  linkedin: false
  pinterest: false
  email: true

social:
  github: intpl

# Google Analytics key, leave blank to ignore
google_analytics_key: "UA-85790551-1"
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: intpl
comments: false

permalink: pretty

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE', 'skillset_builder.rb', 'skillset.json']

plugins:
  - jekyll-seo-tag
  - jekyll-toc
